spring:
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/ordersystem
    username: root
    password: 1234

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
#  스프링 밑에 유레카 이름 설정하는 곳임
#  memberService라는 이름으로 eureka에 등록을 하겠다
  application:
    name: product-service
  #    kafka 설정 정보(consumer의 설정 정보)
  kafka:
    kafka-server: localhost:9092
    consumer:
#      grout-id 는 컨슈머 그룹을 식별하는 ID 로써 , 동일한 그룹 ID를 가진 컨슈머들은 메시지를 분담해서 consume.
      group-id: product-group
#      가장 처음들어온 메시지부터 읽기 시작.(latest: 현시점 이후로 들어오는 메시지만 읽음)
      auto-offset-reset: earliest

#유레카를 바라보자! 라고 하는 설정
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  #  port번호 0으로 지정시 임의숫자값으로  port 실행
  port: 0

jwt:
  expiration: 50000
  # 인코딩 된 32자 이상 필요.(특수문자 사용 안됨)
  # beyoundaccesstokensecretkeybeyoundaccesstokensecretkeybeyoundaccesstokensecretkey
  secretKey: YmV5b3VuZGFjY2Vzc3Rva2Vuc2VjcmV0a2V5YmV5b3VuZGFjY2Vzc3Rva2Vuc2VjcmV0a2V5YmV5b3VuZGFjY2Vzc3Rva2Vuc2VjcmV0a2V5

  # beyoundrefreshtokensecretkeybeyoundrefreshtokensecretkeybeyoundrefreshtokensecretkey
  expirationRt: 288000
  secretKeyRt: YmV5b3VuZHJlZnJlc2h0b2tlbnNlY3JldGtleWJleW91bmRyZWZyZXNodG9rZW5zZWNyZXRrZXliZXlvdW5kcmVmcmVzaHRva2Vuc2VjcmV0a2V5

